In [1]:
import numpy as np
import pandas as pd

In [3]:
"Qasim" in ["Asif","Nasir","Noman","Jasim"]

True

In [4]:
"Qasim" in ["Asif","Nasir","Noman","Jasim","Qasim"]

True

In [5]:
"Qasim" in ("Asif","Nasir","Noman","Jasim","Qasim")

True

In [6]:
"Qasim" in "Pakistan zinda bad!"

False

In [7]:
"Qasim" in "Pakistan zinda Qasim bad!"

True

In [14]:
%%time
names = ['Qasim',"Asif","Nasir","Nomand","Hamza"]
search_names = ["Inam",'Anees']
for s_name in search_names:
    print(s_name in names)
 

False
False
CPU times: user 1.36 ms, sys: 0 ns, total: 1.36 ms
Wall time: 999 µs


# np.in1d()

In [16]:
names = ['Qasim',"Asif","Nasir","Nomand","Hamza"]
search_names = ["Inam",'Anees',"Asif"]

np.in1d(search_names, names)

array([False, False,  True])

In [19]:
b = np.arange(2*2).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [17]:
a = np.arange(4*4).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.in1d(b.ravel(),a.ravel()).reshape(2,2)

array([[ True,  True],
       [ True,  True]])

# np.where
look like if condition

In [27]:
a = np.arange(1,100, 50).reshape(10,5)
a

array([[71, 20, 11, 67, 76],
       [64, 41, 62, 33, 72],
       [14, 73, 56, 32, 76],
       [52, 11, 51, 60, 45],
       [32, 78, 35, 25, 43],
       [26, 85, 60, 87, 97],
       [44, 19, 21, 62,  6],
       [56, 52, 16, 93, 99],
       [85, 63, 98, 18, 90],
       [53, 45, 26, 74, 34]])

In [28]:
np.where(a%2==0, "Even","Odd")

array([['Odd', 'Even', 'Odd', 'Odd', 'Even'],
       ['Even', 'Odd', 'Even', 'Odd', 'Even'],
       ['Even', 'Odd', 'Even', 'Even', 'Even'],
       ['Even', 'Odd', 'Odd', 'Even', 'Odd'],
       ['Even', 'Even', 'Odd', 'Odd', 'Odd'],
       ['Even', 'Odd', 'Even', 'Odd', 'Odd'],
       ['Even', 'Odd', 'Odd', 'Even', 'Even'],
       ['Even', 'Even', 'Even', 'Odd', 'Odd'],
       ['Odd', 'Odd', 'Even', 'Even', 'Even'],
       ['Odd', 'Odd', 'Even', 'Even', 'Even']], dtype='<U4')

In [37]:
rangetoLook = np.arange(1,1001)
rangetoLook

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [40]:
generated =np.random.randint(1,1000,1)

print(generated)

np.where(rangetoLook == generated,"Winner","-")



[617]


array(['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-

In [45]:
generated =np.random.randint(1,1000,2)

print(generated)

WinnerArray = []
np.where(np.in1d(rangetoLook, generated),WinnerArray.append(generated),False)
WinnerArray

[ 16 719]


[array([ 16, 719])]

In [47]:
bonds = np.arange(100).reshape(10,10)
bonds

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [57]:
samples = np.random.choice(bonds.ravel(),10)
samples

array([15,  2, 79, 74, 71,  9, 54, 51, 63, 62])

In [62]:
np.where(np.in1d(bonds,samples),"Winner","Loser")

array(['Loser', 'Loser', 'Winner', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Loser', 'Winner', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Winner', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Loser', 'Winner', 'Loser', 'Loser', 'Winner', 'Loser',
       'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Winner',
       'Winner', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Winner', 'Loser', 'Loser', 'Winner', 'Loser', 'Loser',
       'Loser', 'Loser', 'Winner', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser',
       'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser', 'Loser',
       'Lo

# Pandas Introduction

In [63]:
# Series
# dataframe

### Series
* int
* float
* date
* object/str
* Boolean

In [65]:
[1,2,3,4]

[1, 2, 3, 4]

In [66]:
a = pd.Series([1,2,3,4])
# show additional index on left side
a

0    1
1    2
2    3
3    4
dtype: int64

In [67]:
a = pd.Series((1,2,3,4))
# show additional index on left side
a

0    1
1    2
2    3
3    4
dtype: int64

In [68]:
a = pd.Series('1234')
# show additional index on left side
a

0    1234
dtype: object

In [69]:
# Create series with dictionary
a = pd.Series({"a":1,
              "b":5,
              "c":100})
a

a      1
b      5
c    100
dtype: int64

In [70]:
a = pd.Series([1,2,3],['a','b','c'])
a

a    1
b    2
c    3
dtype: int64

In [74]:
pd.Series(range(1,10))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [76]:
chr(65)

'A'

In [77]:
ord("A")

65

In [80]:
v =  [chr(i) for i in range(65,91)]
k = list(range(65,91))
a = pd.Series(k,v)
a

A    65
B    66
C    67
D    68
E    69
F    70
G    71
H    72
I    73
J    74
K    75
L    76
M    77
N    78
O    79
P    80
Q    81
R    82
S    83
T    84
U    85
V    86
W    87
X    88
Y    89
Z    90
dtype: int64

In [82]:
pd.date_range('2022-01-01','2022-01-10')

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10'],
              dtype='datetime64[ns]', freq='D')

In [102]:
pd.date_range('2022-01-01','2022-01-02', freq="5H")

DatetimeIndex(['2022-01-01 00:00:00', '2022-01-01 05:00:00',
               '2022-01-01 10:00:00', '2022-01-01 15:00:00',
               '2022-01-01 20:00:00'],
              dtype='datetime64[ns]', freq='5H')

0     2
1     2
2     4
3     2
4     1
5     3
6     2
7     2
8     4
9     4
10    4
11    4
12    1
13    3
14    3
15    2
16    4
17    2
18    1
19    4
dtype: int64

In [88]:
city_codes = pd.Series(np.random.randint(1,5,20))
print("city codes",city_codes)

city_mapping = {
    1:"Karachi",
    2:"Islamabad",
    3:"Lahore",
    4:"Faislabad",
    5:"Larkana"
}
print("city mapping",city_mapping)
city_codes.map(city_mapping)

city codes 0     3
1     1
2     1
3     4
4     1
5     2
6     1
7     3
8     3
9     2
10    4
11    3
12    2
13    3
14    3
15    3
16    4
17    1
18    3
19    3
dtype: int64
city mapping {1: 'Karachi', 2: 'Islamabad', 3: 'Lahore', 4: 'Faislabad', 5: 'Larkana'}


0        Lahore
1       Karachi
2       Karachi
3     Faislabad
4       Karachi
5     Islamabad
6       Karachi
7        Lahore
8        Lahore
9     Islamabad
10    Faislabad
11       Lahore
12    Islamabad
13       Lahore
14       Lahore
15       Lahore
16    Faislabad
17      Karachi
18       Lahore
19       Lahore
dtype: object

0     Islamabad
1     Islamabad
2     Faislabad
3     Islamabad
4       Karachi
5        Lahore
6     Islamabad
7     Islamabad
8     Faislabad
9     Faislabad
10    Faislabad
11    Faislabad
12      Karachi
13       Lahore
14       Lahore
15    Islamabad
16    Faislabad
17    Islamabad
18      Karachi
19    Faislabad
dtype: object

In [90]:
messages = pd.Series([
    "I love my country, abc Pakistan zinda bad",
    "I love my country, abc ICAP Pakistan zinda bad",
    "I love my country, abc ICAP one of the perfect institute in Pakistan zinda bad"
])
messages

0            I love my country, abc Pakistan zinda bad
1       I love my country, abc ICAP Pakistan zinda bad
2    I love my country, abc ICAP one of the perfect...
dtype: object

In [97]:
def fn_find_icap(x):
    x = x.lower()
    if "icap" in x:
        return "ICAP"

icap_check = messages.apply(fn_find_icap)
icap_check

0    None
1    ICAP
2    ICAP
dtype: object

In [95]:
for msg in messages:
    print(fn_find_icap(msg))

None
ICAP
ICAP


In [94]:
pd.concat([messages,icap_check], axis=1)

0     1
0          I love my country, abc Pakistan zinda bad  None
1     I love my country, abc ICAP Pakistan zinda bad  ICAP
2  I love my country, abc ICAP one of the perfect...  ICAP

In [100]:
def fn_find_icap_pk(x):
    x = x.lower()
    if "icap" in x and "pakistan" in x:
        return "ICAP-PAKISTAN"

icap_pk_check = messages.apply(fn_find_icap_pk)
pd.concat([messages,icap_pk_check], axis=1)

0              1
0          I love my country, abc Pakistan zinda bad           None
1     I love my country, abc ICAP Pakistan zinda bad  ICAP-PAKISTAN
2  I love my country, abc ICAP one of the perfect...  ICAP-PAKISTAN