# Classes and Objects 

In [7]:
class Human():
    name = "Nasir"
    height = 5.10
    age = 23
    weight = 65
    blood_gp = "B+"
    gender = "Male"
    
    def walk():
        print("Our human is walking")
        
    def eat():
        print("Our human is eating")
    

In [8]:
human1 = Human()

In [9]:
human1.name

'Nasir'

In [10]:
human2 = Human()

In [11]:
human2.name

'Nasir'

In [35]:
class Human():
    def __init__(self,name, age, gender, bg):
        self.name = name
        self.age = age
        self.gender = gender
        self.blood_gp =bg          
       
    def walk(self):
        print(f"Our human {self.name} is walking")
        
    def eat(self):
        print(f"Our human {self.name}is eating")
    

In [13]:
human1 = Human()

TypeError: __init__() missing 4 required positional arguments: 'name', 'age', 'gender', and 'bg'

In [22]:
human1  = Human("Ali", 23, 'Male', "B+")

In [23]:
human2  = Human("Asad", 45, 'Male', "A+")

In [24]:
human1.name

'Ali'

In [25]:
human2.name

'Asad'

In [26]:
human1.walk()

Our human Ali is walking


In [27]:
human1.eat()

Our human Aliis eating


In [28]:
human1.age

23

In [39]:
human4= Human("Hamid", 45, "Male", "B+", "6ft")

TypeError: __init__() takes 5 positional arguments but 6 were given

In [29]:
human1.name

'Ali'

In [30]:
human2.age

45

In [34]:
human2.walk()

Our human Asad is walking


In [32]:
human1.walk()

human2.walk()

Our human Ali is walking


In [37]:
human3= Human("abcd", 2, "Male", "A")

In [38]:
human3.walk()

TypeError: walk() takes 0 positional arguments but 1 was given

# Reference:
https://www.tutorialspoint.com/python/python_classes_objects.htm

In [44]:
import numpy as np

In [52]:
%%time
# normal list or python code
a = [i+5*2/3 for i in range(1,1000000)]
a

CPU times: user 78.4 ms, sys: 7.73 ms, total: 86.1 ms
Wall time: 83.7 ms


[4.333333333333334,
 5.333333333333334,
 6.333333333333334,
 7.333333333333334,
 8.333333333333334,
 9.333333333333334,
 10.333333333333334,
 11.333333333333334,
 12.333333333333334,
 13.333333333333334,
 14.333333333333334,
 15.333333333333334,
 16.333333333333332,
 17.333333333333332,
 18.333333333333332,
 19.333333333333332,
 20.333333333333332,
 21.333333333333332,
 22.333333333333332,
 23.333333333333332,
 24.333333333333332,
 25.333333333333332,
 26.333333333333332,
 27.333333333333332,
 28.333333333333332,
 29.333333333333332,
 30.333333333333332,
 31.333333333333332,
 32.333333333333336,
 33.333333333333336,
 34.333333333333336,
 35.333333333333336,
 36.333333333333336,
 37.333333333333336,
 38.333333333333336,
 39.333333333333336,
 40.333333333333336,
 41.333333333333336,
 42.333333333333336,
 43.333333333333336,
 44.333333333333336,
 45.333333333333336,
 46.333333333333336,
 47.333333333333336,
 48.333333333333336,
 49.333333333333336,
 50.333333333333336,
 51.333333333333336

In [45]:
alist = [1,2,3,4,5,6,7,8,9,10]
anumpy_array = np.array(alist)

print(type(alist))
print(type(anumpy_array))

<class 'list'>
<class 'numpy.ndarray'>


In [47]:
alist + 5

TypeError: can only concatenate list (not "int") to list

In [46]:
2 + 5

7

In [49]:
anumpy_array + 5 * 2 / 3

array([ 4.33333333,  5.33333333,  6.33333333,  7.33333333,  8.33333333,
        9.33333333, 10.33333333, 11.33333333, 12.33333333, 13.33333333])

In [53]:
%%time
b = np.arange(1,1000000) + 5 * 2 / 3
b.size

CPU times: user 24.4 ms, sys: 9.32 ms, total: 33.7 ms
Wall time: 31.2 ms


999999

In [51]:
35.4 / 84.6

0.41843971631205673

In [54]:
np.array([1,True,"Pakistan"])

array(['1', 'True', 'Pakistan'], dtype='<U21')

In [55]:
a = [1,2,3]
b = [2,4,5]

for i,j in zip(a,b):
    print(i,j, "=" ,i+j)

1 2 = 3
2 4 = 6
3 5 = 8


In [60]:
a = np.array([1,2,3])
b = np.array([2,4,5])

a + b

array([3, 6, 8])

In [61]:
a = np.arange(1,10)
b = np.arange(11,20)
c = np.arange(21,30)
d = np.arange(31,40)
print(a,b,c,d, sep="\n")


[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[21 22 23 24 25 26 27 28 29]
[31 32 33 34 35 36 37 38 39]


In [62]:
a + b * c / d

array([ 8.4516129 , 10.25      , 12.06060606, 13.88235294, 15.71428571,
       17.55555556, 19.40540541, 21.26315789, 23.12820513])

In [64]:
a = np.asarray([1,2,3])
a

array([1, 2, 3])

In [65]:
a = np.array([1,2,3], dtype=np.float64)
a

array([1., 2., 3.])

In [69]:
a = np.array(list("pakistan"))
a

array('pakistan', dtype='<U8')

In [70]:
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [72]:
a = np.arange(1,101).reshape((10,10))
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
15 rows and 20 columns

In [73]:
2*a

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100],
       [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
       [122, 124, 126, 128, 130, 132, 134, 136, 138, 140],
       [142, 144, 146, 148, 150, 152, 154, 156, 158, 160],
       [162, 164, 166, 168, 170, 172, 174, 176, 178, 180],
       [182, 184, 186, 188, 190, 192, 194, 196, 198, 200]])

In [59]:
a = [(i,j) for i in range(1,10)
    for j in range(1,10)]
a

[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6),
 (6, 7),
 (6, 8),
 (6, 9),
 (7, 1),
 (7, 2),
 (7, 3),
 (7, 4),
 (7, 5),
 (7, 6),
 (7, 7),
 (7, 8),
 (7, 9),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (8, 5),
 (8, 6),
 (8, 7),
 (8, 8),
 (8, 9),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4),
 (9, 5),
 (9, 6),
 (9, 7),
 (9, 8),
 (9, 9)]

In [74]:
a = np.array([1,2,3,4])
# 

In [75]:
a

array([1, 2, 3, 4])

In [76]:
b = np.array(range(5))

In [77]:
b

array([0, 1, 2, 3, 4])

In [78]:
c = np.arange(5)
c

array([0, 1, 2, 3, 4])

In [79]:
a *5

array([ 5, 10, 15, 20])

In [80]:
a+9

array([10, 11, 12, 13])

In [81]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [82]:
a.shape

(4,)

In [83]:
# MEMBERS
# DIMENSIONS

In [84]:
a.ndim

1

In [96]:
arr2d =np.arange(16).reshape(4,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
arr2d.shape

(4, 4)

In [89]:
arr2d.ndim

2

In [91]:
arr3d = arr2d.reshape(2,2,4)

In [92]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [93]:
arr3d.ndim

3

In [94]:
arr1d  = arr3d.reshape(16)

In [95]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])