In [3]:
class Toye_Car():
    
    def __init__(self, p_color, p_model, p_engin_capacity):
        self.color = p_color
        self.model = p_model
        self.engine_capacity = p_engin_capacity
    
    def car_start():
        pass
    
    def car_switch_off():
        pass
    
toy1 = Toye_Car('red','2022','1000CC')    
toy2 = Toye_Car('red','2022','850CC')  

print(toy1.engine_capacity)
print(toy2.engine_capacity)


1000CC
850CC


In [4]:
class Toye_Car():
    
    def __init__(alpha, p_color, p_model, p_engin_capacity):
        alpha.color = p_color
        alpha.model = p_model
        alpha.engine_capacity = p_engin_capacity
    
    def car_start():
        pass
    
    def car_switch_off():
        pass
    
toy1 = Toye_Car('red','2022','1000CC')    
toy2 = Toye_Car('red','2022','850CC')  

print(toy1.engine_capacity)
print(toy2.engine_capacity)


1000CC
850CC


In [1]:
import mera_package

In [2]:
print(mera_package.owner_name)

Nasir Hussain


In [8]:
print(mera_package.class_name)

class8


In [9]:
mera_package.greeting("Muhammad Qasim")

'Hello Mr/Miss Muhammad Qasim. Welcome in online session'

In [10]:
mera_package.agenda_meeting("OOP")

'OOP we will cover it.'

# Numpy

In [3]:
import numpy as np

In [4]:
# 10 timer faster
# performe numerical operation with very simple way

In [6]:
%%time
[i+2 for i in range(1,1000000)]

CPU times: user 58.8 ms, sys: 17.6 ms, total: 76.4 ms
Wall time: 91.2 ms


[3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,


In [ ]:
for i in range(1,1000000):
    print(i+5)

In [9]:
[1,2,3,5] + 5

TypeError: can only concatenate list (not "int") to list

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11) + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
print(np.arange(1,11))
np.arange(1,11) + 2 - 3 * 3

[ 1  2  3  4  5  6  7  8  9 10]


array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3])

In [18]:
%%time
np.arange(1,1000000) + 2

CPU times: user 3.02 ms, sys: 20.8 ms, total: 23.9 ms
Wall time: 35.4 ms


array([      3,       4,       5, ...,  999999, 1000000, 1000001])

In [19]:
35.4 / 91.2 * 100

38.81578947368421

In [23]:
# brodcasting
print(np.arange(1,11))
print(np.arange(1,11)+2)


np.arange(1,11) + np.array([2,2,2,2,2,2,2,2,2,2])

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10 11 12]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
a = np.arange(1,11) % 3 == 0
a

array([False, False,  True, False, False,  True, False, False,  True,
       False])

In [28]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[[True,False,True,False,False,False,False,False,False,True]]

array([ 1,  3, 10])

In [34]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a % 3 == 0)
a[a % 3 == 0]

[False False  True False False  True False False  True False]


array([3, 6, 9])

In [ ]:
3,5,7


In [35]:
a = np.arange(1,1000)
a[(a%3==0) & (a%5==0) & (a%7==0)]# and &

array([105, 210, 315, 420, 525, 630, 735, 840, 945])

In [36]:
a = np.arange(1,100)
a[(a%3==0) | (a%5==0) | (a%7==0)]# or |

array([ 3,  5,  6,  7,  9, 10, 12, 14, 15, 18, 20, 21, 24, 25, 27, 28, 30,
       33, 35, 36, 39, 40, 42, 45, 48, 49, 50, 51, 54, 55, 56, 57, 60, 63,
       65, 66, 69, 70, 72, 75, 77, 78, 80, 81, 84, 85, 87, 90, 91, 93, 95,
       96, 98, 99])

In [ ]:
3 ,5 and
8 or

In [37]:
a = np.arange(1,100)
a[((a%3==0) & (a%5==0)) | (a%8==0)]# or |

array([ 8, 15, 16, 24, 30, 32, 40, 45, 48, 56, 60, 64, 72, 75, 80, 88, 90,
       96])

In [38]:
a[((a%3==0) & (a%5==0)) | ((a%9==0) & (a%15==0))]# or |

array([15, 30, 45, 60, 75, 90])

In [ ]:
(3,5 and)
or
(9,15 and)

# array dimension1

In [46]:
a = np.array(2) # scalar value
print(a)
print(a.shape)
print(a.ndim)# dimension
print(a.size)

2
()
0
1


In [47]:
a = np.array([1,2,3,4,5]) # vector
print(a)
print(a.shape)
print(a.ndim)# dimension
print(a.size)

[1 2 3 4 5]
(5,)
1
5


In [48]:
a = np.array([[1,2,3,4,5],
             [6,7,8,9,10]]) # vector
print(a)

print(a.shape)
print(a.ndim)# dimension
print(a.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2
10


In [54]:
a = np.arange(3*4*4).reshape((3,4,4))
print(a)

print(a.shape)
print(a.ndim)# dimension
print(a.size)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
(3, 4, 4)
3
48


In [55]:
a = np.arange(3*4*4).reshape((3,4,4))
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


In [58]:
a[2]

array([[32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])

In [62]:
a = np.arange(3*4*4).reshape((3,4,4))
print(a)
a[0,2,2]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


10

In [63]:
a = np.arange(3*4*4).reshape((3,4,4))
print(a)
a[1,3,1] # [slide,row,colum]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [64]:
a = np.arange(3*4*4).reshape((3,4,4))
print(a)
(a % 3==0) & (a%5==0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False,  True, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False,  True, False, False]]])

In [68]:
a = np.arange(1,101)
print(a)
print(a.reshape((10,10)))


[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [79]:
a = np.arange(1,51)
a = a.reshape((10,5))
print(a)
(a%3==0) &( a %5 == 0)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [78]:
a.shape

(10, 5)

# arange
# reshape
# ones
# zeros
# np.in1d
# np.where

In [80]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
np.ones((10,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

# in1d

In [84]:
"Qasim" in "Pakistan zinda bad, we love our country!"

False

In [85]:
"Qasim" in "Pakistan zinda bad, Qasim love our country!"

True

In [86]:
"Qasim" in ["Nasir","Noman","Naveed"]

False

In [87]:
"Qasim" in ["Nasir","Noman","Qasim","Naveed"]

True

In [88]:
"Qasim" in ("Nasir","Noman","Qasim","Naveed")

True

# in 
* find scalar value in iterator datatypes (string,list,tuple, dict keys)

# np.in1d()
* find vector(1 diminsion array) value in iterator datatypes (list,tuple, dict keys)


In [92]:
names = ["Nasir","Noman","Qasim","Naveed","Konain","Rashid","Iqbal",'Ebad']

search_names = ['Asif',"Rashid","Hamza","Noman"]

np.in1d(search_names,names)
# search_names search in names list
# return boolean array shape same as search_name array


array([False,  True, False,  True])

In [102]:
names = np.array(["Nasir","Noman","Qasim","Naveed","Konain","Rashid","Iqbal",'Ebad'])

search_names = np.array(['Asif',"Rashid","Hamza","Noman"])

search_names[np.in1d(search_names,names)]
# search_names search in names list
# return boolean array shape same as search_name array


array(['Rashid', 'Noman'], dtype='<U6')

In [95]:
names = ["Nasir","Noman","Qasim","Naveed","Konain","Rashid","Iqbal",'Ebad']

search_names = ['Asif',"Rashid","Hamza","Noman"]

l = []
for sname in search_names:
    l.append(sname in names)
    
l    

[False, True, False, True]

In [103]:
a = np.arange(1,100)
print(a)
np.where(a%2==0, "Even","Odd")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


array(['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd'],
      dtype='<U4')

In [105]:
a = np.array([1,2,5,7])
b = np.array([3,7,2,9])

np.where(a>b, a, b)

array([3, 7, 5, 9])